
'''
# Oracle 데이터베이스에 접속
conn = cx_Oracle.connect('hr/hr@localhost/xe')
print("Connected to Oracle Database")
# board 테이블 생성
cur = conn.cursor()
cur.execute('DROP TABLE board')
cur.execute('CREATE TABLE board (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, title VARCHAR2(100), content VARCHAR2(4000), created_at DATE DEFAULT SYSDATE, updated_at DATE DEFAULT SYSDATE)')
print("board table created")
# 테이블 생성 후 커서와 연결 종료
cur.close()
conn.close()
'''
import cx_Oracle

# 데이터베이스 접속 정보
username = 'hr'
password = 'hr'
host = 'localhost'
port = '31521'
sid = 'xe'
dsn = cx_Oracle.makedsn(host, port, sid)

# 데이터베이스 연결
conn = cx_Oracle.connect(username, password, dsn)
cur = conn.cursor()

# SQL 문 실행
sql = 'SELECT employee_id, first_name, last_name, email FROM employees ORDER BY employee_id'
cur.execute(sql)

# 결과 출력

for row in cur:
    print(row)

# 데이터베이스 연결 해제
cur.close()
conn.close()